version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - rails6-postgresql-data:/var/lib/postgresql/data
      - ./docker/init/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PRODUCTION_DB
    ports:
      - '5432'
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    working_dir: /myapp
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp:cached
      - /myapp/log
      - /myapp/.git
      - /myapp/tmp
      - /myapp/node_modules
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    tty: true
    stdin_open: true
    depends_on:
      - postgres
volumes:
  rails6-postgresql-data:
    driver: local
